### ISSUE TITLE
Segmentation fault on account enable

### ISSUE THREAD

**Issue by meersjo** [xnamed/purple-hangouts#1]
Hey,

I've been using this plugin happily for several months, but it recently stopped working - consistently segfaults when I enable the account using it.

I sometimes, but not always, get these on the console:
```
(Pidgin:12278): Json-CRITICAL **: json_object_has_member: assertion 'object != NULL' failed
(Pidgin:12278): Json-CRITICAL **: json_object_has_member: assertion 'object != NULL' failed
(Pidgin:12278): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed
```

I captured a core file, but at 215MB it might be slightly too large to upload here :-) I'm attaching the backtrace, as captured by catchsegv.

I'm running the Ubuntu Trusty package from the webupd8 PPA, version 1.0+hg20160826-1 - from that datestamp and the last commit in here I would assume that's the latest version or close to?

System is Linux Mint 17.3 (≃Ubuntu Trusty) on 64-bit.

I've currently fallen back to the xmmp plugin, thank you for any help you can offer. Please let me know if there is more information I can provide.

/Johan

[backtrace-piding-purple-hangouts-20161010-1010.txt](https://github.com/xnamed/purple-hangouts/files/519008/backtrace-piding-purple-hangouts-20161010-1010.txt)

**Comment by xnamed** [comment]
Sorry, don't know about Pidgin i only use libpurple for Speatrum.im transports.

**Comment by meersjo** [comment]
The pidgin part should be unrelated; it only crashes as soon as this library is enabled. Am I mistaken in thinking that your repo is the origin of this code?

**Comment by xnamed** [comment]
yes, original repository: https://bitbucket.org/EionRobb/purple-hangouts/

**Comment by meersjo** [comment]
Aha, thank you. i'll take this over there.
